version: "3.9"

services:
  db:
    image: postgres:15
    container_name: baseapp_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"          # opcional, solo si quieres acceder desde tu host
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baseapp_api
    env_file:
      - ./backend/.env
    environment:
      # Si prefieres inyectarlo aquí en vez de .env, puedes hacerlo:
      DATABASE_URL: ${DATABASE_URL}
      FLASK_ENV: production
      PORT: 8000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  db_data:
